/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取房间列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Room"][];
                    };
                };
            };
        };
        put?: never;
        /** 创建房间 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRoomRequest"];
                };
            };
            responses: {
                /** @description 创建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Room"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取房间详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Room"];
                    };
                };
                /** @description 房间不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 加入房间 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description 房间密码（如果需要） */
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description 加入成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Room"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 解析视频源 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ParseVideoRequest"];
                };
            };
            responses: {
                /** @description 解析成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VideoSource"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Room: {
            /** @example room-123 */
            id: string;
            /** @example 我的观影房间 */
            name: string;
            /** @example user-456 */
            ownerId: string;
            /** @example 张三 */
            ownerName?: string;
            /** @example true */
            isActive: boolean;
            /** @example 5 */
            userCount?: number;
            /** @example 20 */
            maxUsers?: number;
            /** Format: date-time */
            createdAt?: string;
            currentVideo?: components["schemas"]["VideoSource"];
        };
        CreateRoomRequest: {
            /** @example 周末观影房 */
            name: string;
            /** @description 可选的房间密码 */
            password?: string;
            /** @default 20 */
            maxUsers: number;
        };
        User: {
            id: string;
            username: string;
            /** Format: uri */
            avatarUrl?: string;
        };
        VideoSource: {
            id: string;
            /**
             * @example bilibili
             * @enum {string}
             */
            type: "bilibili" | "quark" | "youtube";
            /**
             * Format: uri
             * @example https://www.bilibili.com/video/BV1xx411c7mD
             */
            url: string;
            /** @example 电影标题 */
            title?: string;
            /** @description 时长（秒） */
            duration?: number;
            /** Format: uri */
            thumbnail?: string;
            /**
             * Format: uri
             * @description 实际播放的视频流地址
             */
            streamUrl?: string;
        };
        ParseVideoRequest: {
            /**
             * Format: uri
             * @example https://www.bilibili.com/video/BV1xx411c7mD
             */
            url: string;
            /**
             * @description 视频源类型，如果不提供会自动识别
             * @enum {string}
             */
            type?: "bilibili" | "quark" | "youtube";
        };
        /** @description 视频播放状态（通过 WebSocket 同步） */
        VideoState: {
            /**
             * Format: double
             * @example 123.45
             */
            currentTime?: number;
            isPlaying?: boolean;
            /**
             * Format: double
             * @default 1
             */
            playbackRate: number;
            /** Format: double */
            volume?: number;
        };
        Error: {
            /** @example ROOM_NOT_FOUND */
            code: string;
            /** @example 房间不存在 */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
