// This file is auto-generated by @hey-api/openapi-ts

export { getRooms, getRoomsByRoomId, type Options, postRooms, postRoomsByRoomIdJoin, postVideosParse } from './sdk.gen';
export type { ClientOptions, CreateRoomRequest, Error, GetRoomsByRoomIdData, GetRoomsByRoomIdError, GetRoomsByRoomIdErrors, GetRoomsByRoomIdResponse, GetRoomsByRoomIdResponses, GetRoomsData, GetRoomsResponse, GetRoomsResponses, ParseVideoRequest, PostRoomsByRoomIdJoinData, PostRoomsByRoomIdJoinResponse, PostRoomsByRoomIdJoinResponses, PostRoomsData, PostRoomsResponse, PostRoomsResponses, PostVideosParseData, PostVideosParseResponse, PostVideosParseResponses, Room, User, VideoSource, VideoState } from './types.gen';
