// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetRoomsByRoomIdData, GetRoomsByRoomIdErrors, GetRoomsByRoomIdResponses, GetRoomsData, GetRoomsResponses, PostRoomsByRoomIdJoinData, PostRoomsByRoomIdJoinResponses, PostRoomsData, PostRoomsResponses, PostVideosParseData, PostVideosParseResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 获取房间列表
 */
export const getRooms = <ThrowOnError extends boolean = false>(options?: Options<GetRoomsData, ThrowOnError>) => (options?.client ?? client).get<GetRoomsResponses, unknown, ThrowOnError>({ url: '/rooms', ...options });

/**
 * 创建房间
 */
export const postRooms = <ThrowOnError extends boolean = false>(options: Options<PostRoomsData, ThrowOnError>) => (options.client ?? client).post<PostRoomsResponses, unknown, ThrowOnError>({
    url: '/rooms',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取房间详情
 */
export const getRoomsByRoomId = <ThrowOnError extends boolean = false>(options: Options<GetRoomsByRoomIdData, ThrowOnError>) => (options.client ?? client).get<GetRoomsByRoomIdResponses, GetRoomsByRoomIdErrors, ThrowOnError>({ url: '/rooms/{roomId}', ...options });

/**
 * 加入房间
 */
export const postRoomsByRoomIdJoin = <ThrowOnError extends boolean = false>(options: Options<PostRoomsByRoomIdJoinData, ThrowOnError>) => (options.client ?? client).post<PostRoomsByRoomIdJoinResponses, unknown, ThrowOnError>({
    url: '/rooms/{roomId}/join',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 解析视频源
 */
export const postVideosParse = <ThrowOnError extends boolean = false>(options: Options<PostVideosParseData, ThrowOnError>) => (options.client ?? client).post<PostVideosParseResponses, unknown, ThrowOnError>({
    url: '/videos/parse',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
