// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/api/v1' | (string & {});
};

export type Room = {
    id: string;
    name: string;
    ownerId: string;
    ownerName?: string;
    isActive: boolean;
    userCount?: number;
    maxUsers?: number;
    createdAt?: string;
    currentVideo?: VideoSource;
};

export type CreateRoomRequest = {
    name: string;
    /**
     * 可选的房间密码
     */
    password?: string;
    maxUsers?: number;
};

export type User = {
    id: string;
    username: string;
    avatarUrl?: string;
};

export type VideoSource = {
    id: string;
    type: 'bilibili' | 'quark' | 'youtube';
    url: string;
    title?: string;
    /**
     * 时长（秒）
     */
    duration?: number;
    thumbnail?: string;
    /**
     * 实际播放的视频流地址
     */
    streamUrl?: string;
};

export type ParseVideoRequest = {
    url: string;
    /**
     * 视频源类型，如果不提供会自动识别
     */
    type?: 'bilibili' | 'quark' | 'youtube';
};

/**
 * 视频播放状态（通过 WebSocket 同步）
 */
export type VideoState = {
    currentTime?: number;
    isPlaying?: boolean;
    playbackRate?: number;
    volume?: number;
};

export type Error = {
    code: string;
    message: string;
};

export type GetRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type GetRoomsResponses = {
    /**
     * 成功
     */
    200: Array<Room>;
};

export type GetRoomsResponse = GetRoomsResponses[keyof GetRoomsResponses];

export type PostRoomsData = {
    body: CreateRoomRequest;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type PostRoomsResponses = {
    /**
     * 创建成功
     */
    201: Room;
};

export type PostRoomsResponse = PostRoomsResponses[keyof PostRoomsResponses];

export type GetRoomsByRoomIdData = {
    body?: never;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/rooms/{roomId}';
};

export type GetRoomsByRoomIdErrors = {
    /**
     * 房间不存在
     */
    404: Error;
};

export type GetRoomsByRoomIdError = GetRoomsByRoomIdErrors[keyof GetRoomsByRoomIdErrors];

export type GetRoomsByRoomIdResponses = {
    /**
     * 成功
     */
    200: Room;
};

export type GetRoomsByRoomIdResponse = GetRoomsByRoomIdResponses[keyof GetRoomsByRoomIdResponses];

export type PostRoomsByRoomIdJoinData = {
    body?: {
        /**
         * 房间密码（如果需要）
         */
        password?: string;
    };
    path: {
        roomId: string;
    };
    query?: never;
    url: '/rooms/{roomId}/join';
};

export type PostRoomsByRoomIdJoinResponses = {
    /**
     * 加入成功
     */
    200: Room;
};

export type PostRoomsByRoomIdJoinResponse = PostRoomsByRoomIdJoinResponses[keyof PostRoomsByRoomIdJoinResponses];

export type PostVideosParseData = {
    body: ParseVideoRequest;
    path?: never;
    query?: never;
    url: '/videos/parse';
};

export type PostVideosParseResponses = {
    /**
     * 解析成功
     */
    200: VideoSource;
};

export type PostVideosParseResponse = PostVideosParseResponses[keyof PostVideosParseResponses];
