// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type RegisterRequest = {
    username: string;
    password: string;
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type AuthResponse = {
    user: User;
    /**
     * JWT 认证令牌
     */
    token: string;
};

export type Room = {
    /**
     * 房间内部 ID
     */
    id: string;
    /**
     * 8位大写房间码，用于加入房间
     */
    code: string;
    name: string;
    ownerId: string;
    ownerName?: string;
    isActive: boolean;
    /**
     * 房间是否需要密码
     */
    hasPassword?: boolean;
    userCount?: number;
    maxUsers?: number;
    createdAt?: string;
    currentVideo?: VideoSource;
    /**
     * 当前用户在此房间的角色
     */
    currentUserRole?: 'host' | 'member' | 'guest';
    /**
     * 当前用户是否有播放控制权限
     */
    currentUserHasControl?: boolean;
};

export type CreateRoomRequest = {
    name: string;
    /**
     * 可选的房间密码
     */
    password?: string;
    maxUsers?: number;
};

export type RecentRoom = {
    room: Room;
    lastVisited: string;
    lastWatchedVideoTitle?: string;
};

export type User = {
    id: string;
    username: string;
    avatarUrl?: string;
};

export type VideoSource = {
    id: string;
    type: 'bilibili' | 'quark' | 'youtube';
    url: string;
    title?: string;
    /**
     * 时长（秒）
     */
    duration?: number;
    thumbnail?: string;
    /**
     * 实际播放的视频流地址
     */
    streamUrl?: string;
};

export type ParseVideoRequest = {
    url: string;
    /**
     * 视频源类型，如果不提供会自动识别
     */
    type?: 'bilibili' | 'quark' | 'youtube';
};

/**
 * 视频播放状态（通过 WebSocket 同步）
 */
export type VideoState = {
    currentTime?: number;
    isPlaying?: boolean;
    playbackRate?: number;
    volume?: number;
};

export type Error = {
    code: string;
    message: string;
};

export type PostAuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * 请求参数错误
     */
    400: Error;
    /**
     * 用户名已存在
     */
    409: Error;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * 注册成功
     */
    201: AuthResponse;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * 用户名或密码错误
     */
    401: Error;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * 登录成功
     */
    200: AuthResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * 登出成功
     */
    204: void;
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeErrors = {
    /**
     * 未登录
     */
    401: Error;
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
    /**
     * 成功
     */
    200: User;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type GetRoomsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/rooms';
};

export type GetRoomsResponses = {
    /**
     * 成功
     */
    200: Array<Room>;
};

export type GetRoomsResponse = GetRoomsResponses[keyof GetRoomsResponses];

export type PostRoomsData = {
    body: CreateRoomRequest;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type PostRoomsErrors = {
    /**
     * 未登录
     */
    401: Error;
};

export type PostRoomsError = PostRoomsErrors[keyof PostRoomsErrors];

export type PostRoomsResponses = {
    /**
     * 创建成功
     */
    201: Room;
};

export type PostRoomsResponse = PostRoomsResponses[keyof PostRoomsResponses];

export type GetRoomsByRoomCodeData = {
    body?: never;
    path: {
        /**
         * 8位大写房间码
         */
        roomCode: string;
    };
    query?: never;
    url: '/rooms/{roomCode}';
};

export type GetRoomsByRoomCodeErrors = {
    /**
     * 房间不存在
     */
    404: Error;
};

export type GetRoomsByRoomCodeError = GetRoomsByRoomCodeErrors[keyof GetRoomsByRoomCodeErrors];

export type GetRoomsByRoomCodeResponses = {
    /**
     * 成功
     */
    200: Room;
};

export type GetRoomsByRoomCodeResponse = GetRoomsByRoomCodeResponses[keyof GetRoomsByRoomCodeResponses];

export type PostRoomsByRoomCodeJoinData = {
    body?: {
        /**
         * 房间密码（如果需要）
         */
        password?: string;
    };
    path: {
        /**
         * 8位大写房间码
         */
        roomCode: string;
    };
    query?: never;
    url: '/rooms/{roomCode}/join';
};

export type PostRoomsByRoomCodeJoinErrors = {
    /**
     * 未登录
     */
    401: Error;
    /**
     * 密码错误
     */
    403: Error;
    /**
     * 房间不存在
     */
    404: Error;
};

export type PostRoomsByRoomCodeJoinError = PostRoomsByRoomCodeJoinErrors[keyof PostRoomsByRoomCodeJoinErrors];

export type PostRoomsByRoomCodeJoinResponses = {
    /**
     * 加入成功
     */
    200: Room;
};

export type PostRoomsByRoomCodeJoinResponse = PostRoomsByRoomCodeJoinResponses[keyof PostRoomsByRoomCodeJoinResponses];

export type GetUsersMeRecentRoomsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/users/me/recent-rooms';
};

export type GetUsersMeRecentRoomsErrors = {
    /**
     * 未登录
     */
    401: Error;
};

export type GetUsersMeRecentRoomsError = GetUsersMeRecentRoomsErrors[keyof GetUsersMeRecentRoomsErrors];

export type GetUsersMeRecentRoomsResponses = {
    /**
     * 成功
     */
    200: Array<RecentRoom>;
};

export type GetUsersMeRecentRoomsResponse = GetUsersMeRecentRoomsResponses[keyof GetUsersMeRecentRoomsResponses];

export type PostVideosParseData = {
    body: ParseVideoRequest;
    path?: never;
    query?: never;
    url: '/videos/parse';
};

export type PostVideosParseErrors = {
    /**
     * 无法解析视频源
     */
    400: Error;
};

export type PostVideosParseError = PostVideosParseErrors[keyof PostVideosParseErrors];

export type PostVideosParseResponses = {
    /**
     * 解析成功
     */
    200: VideoSource;
};

export type PostVideosParseResponse = PostVideosParseResponses[keyof PostVideosParseResponses];
