// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ParseVideoRequestType.
const (
	ParseVideoRequestTypeBilibili ParseVideoRequestType = "bilibili"
	ParseVideoRequestTypeQuark    ParseVideoRequestType = "quark"
	ParseVideoRequestTypeYoutube  ParseVideoRequestType = "youtube"
)

// Defines values for VideoSourceType.
const (
	VideoSourceTypeBilibili VideoSourceType = "bilibili"
	VideoSourceTypeQuark    VideoSourceType = "quark"
	VideoSourceTypeYoutube  VideoSourceType = "youtube"
)

// CreateRoomRequest defines model for CreateRoomRequest.
type CreateRoomRequest struct {
	MaxUsers *int   `json:"maxUsers,omitempty"`
	Name     string `json:"name"`

	// Password 可选的房间密码
	Password *string `json:"password,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ParseVideoRequest defines model for ParseVideoRequest.
type ParseVideoRequest struct {
	// Type 视频源类型，如果不提供会自动识别
	Type *ParseVideoRequestType `json:"type,omitempty"`
	Url  string                 `json:"url"`
}

// ParseVideoRequestType 视频源类型，如果不提供会自动识别
type ParseVideoRequestType string

// Room defines model for Room.
type Room struct {
	CreatedAt    *time.Time   `json:"createdAt,omitempty"`
	CurrentVideo *VideoSource `json:"currentVideo,omitempty"`
	Id           string       `json:"id"`
	IsActive     bool         `json:"isActive"`
	MaxUsers     *int         `json:"maxUsers,omitempty"`
	Name         string       `json:"name"`
	OwnerId      string       `json:"ownerId"`
	OwnerName    *string      `json:"ownerName,omitempty"`
	UserCount    *int         `json:"userCount,omitempty"`
}

// VideoSource defines model for VideoSource.
type VideoSource struct {
	// Duration 时长（秒）
	Duration *int   `json:"duration,omitempty"`
	Id       string `json:"id"`

	// StreamUrl 实际播放的视频流地址
	StreamUrl *string         `json:"streamUrl,omitempty"`
	Thumbnail *string         `json:"thumbnail,omitempty"`
	Title     *string         `json:"title,omitempty"`
	Type      VideoSourceType `json:"type"`
	Url       string          `json:"url"`
}

// VideoSourceType defines model for VideoSource.Type.
type VideoSourceType string

// PostRoomsRoomIdJoinJSONBody defines parameters for PostRoomsRoomIdJoin.
type PostRoomsRoomIdJoinJSONBody struct {
	// Password 房间密码（如果需要）
	Password *string `json:"password,omitempty"`
}

// PostRoomsJSONRequestBody defines body for PostRooms for application/json ContentType.
type PostRoomsJSONRequestBody = CreateRoomRequest

// PostRoomsRoomIdJoinJSONRequestBody defines body for PostRoomsRoomIdJoin for application/json ContentType.
type PostRoomsRoomIdJoinJSONRequestBody PostRoomsRoomIdJoinJSONBody

// PostVideosParseJSONRequestBody defines body for PostVideosParse for application/json ContentType.
type PostVideosParseJSONRequestBody = ParseVideoRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 获取房间列表
	// (GET /rooms)
	GetRooms(c *gin.Context)
	// 创建房间
	// (POST /rooms)
	PostRooms(c *gin.Context)
	// 获取房间详情
	// (GET /rooms/{roomId})
	GetRoomsRoomId(c *gin.Context, roomId string)
	// 加入房间
	// (POST /rooms/{roomId}/join)
	PostRoomsRoomIdJoin(c *gin.Context, roomId string)
	// 解析视频源
	// (POST /videos/parse)
	PostVideosParse(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetRooms operation middleware
func (siw *ServerInterfaceWrapper) GetRooms(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRooms(c)
}

// PostRooms operation middleware
func (siw *ServerInterfaceWrapper) PostRooms(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostRooms(c)
}

// GetRoomsRoomId operation middleware
func (siw *ServerInterfaceWrapper) GetRoomsRoomId(c *gin.Context) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", c.Param("roomId"), &roomId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter roomId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRoomsRoomId(c, roomId)
}

// PostRoomsRoomIdJoin operation middleware
func (siw *ServerInterfaceWrapper) PostRoomsRoomIdJoin(c *gin.Context) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", c.Param("roomId"), &roomId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter roomId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostRoomsRoomIdJoin(c, roomId)
}

// PostVideosParse operation middleware
func (siw *ServerInterfaceWrapper) PostVideosParse(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostVideosParse(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/rooms", wrapper.GetRooms)
	router.POST(options.BaseURL+"/rooms", wrapper.PostRooms)
	router.GET(options.BaseURL+"/rooms/:roomId", wrapper.GetRoomsRoomId)
	router.POST(options.BaseURL+"/rooms/:roomId/join", wrapper.PostRoomsRoomIdJoin)
	router.POST(options.BaseURL+"/videos/parse", wrapper.PostVideosParse)
}
